# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
    ]
