# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajaAhorros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('siglas', models.CharField(max_length=10)),
                ('logo', models.FilePathField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
    ]
