# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(default='direccion', max_length=10)),
                ('genero', models.CharField(choices=[('m', 'masculino'), ('f', 'femenino')], max_length=10)),
                ('estadoCivil', models.CharField(choices=[('soltero', 'soltero'), ('divorciado', 'divorciado'), ('casado', 'casado'), ('viudo', 'viudo')], max_length=10)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cajaahorros',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cajaahorros',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cliente',
            name='idCA',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='caja.CajaAhorros'),
        ),
    ]
