# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_transaccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentaahorros',
            old_name='idC',
            new_name='cliente',
        ),
    ]
