# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_auto_20160607_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('divorciado', 'divorciado'), ('soltero', 'soltero'), ('viudo', 'viudo'), ('casado', 'casado')], max_length=10),
        ),
    ]
