# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_auto_20160619_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('soltero', 'soltero'), ('viudo', 'viudo'), ('casado', 'casado'), ('divorciado', 'divorciado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino')], max_length=10),
        ),
    ]
