# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_auto_20160711_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('soltero', 'soltero'), ('viudo', 'viudo'), ('divorciado', 'divorciado'), ('casado', 'casado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('retiro', 'retiro'), ('deposito', 'deposito')], max_length=30),
        ),
    ]
